"""update aishorasub schema

Revision ID: 2cc2104ecc47
Revises: bae2994cb0dd
Create Date: 2026-09-22 13:43:06.080606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc2104ecc47'
down_revision: Union[str, Sequence[str], None] = 'bae2994cb0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'bulk_sms_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'exams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=10), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_table(
        'bonus_transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=250), nullable=False),
        sa.Column('message', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('old_balance', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('new_balance', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('txn_type', sa.String(length=20), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_bonus_transactions_reference'),
        'bonus_transactions',
        ['reference'],
        unique=True
    )
    op.create_index(
        op.f('ix_bonus_transactions_status'),
        'bonus_transactions',
        ['status'],
        unique=False
    )
    op.create_index(
        op.f('ix_bonus_transactions_user_id'),
        'bonus_transactions',
        ['user_id'],
        unique=False
    )

    op.create_table(
        'exam_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('discount_type', sa.String(length=10), nullable=False),
        sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('agent_discount_type', sa.String(length=10), nullable=False),
        sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('api_discount_type', sa.String(length=10), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_exam_plans_exam_id'),
        'exam_plans',
        ['exam_id'],
        unique=False
    )

    op.create_table(
        'kyc_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_type', sa.String(length=20), nullable=False),
        sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('provider', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ['provider'],
            ['payment_providers.name'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_type')
    )

    op.create_table(
        'otps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('otp', sa.String(length=250), nullable=False),
        sa.Column('expiry_time', sa.DateTime(), nullable=False),
        sa.Column('token', sa.String(length=250), nullable=True),
        sa.Column('token_expiry_time', sa.DateTime(), nullable=True),
        sa.Column('is_used', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_otps_user_id'),
        'otps',
        ['user_id'],
        unique=False
    )

    op.create_table(
        'provider_exams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('provider_exam_id', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_provider_exams_exam_id'),
        'provider_exams',
        ['exam_id'],
        unique=False
    )

    op.create_table(
        'user_kycs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('middle_name', sa.String(length=20), nullable=True),
        sa.Column('last_name', sa.String(length=20), nullable=True),
        sa.Column('full_name', sa.String(length=100), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=20), nullable=True),
        sa.Column('gender', sa.String(length=10), nullable=True),
        sa.Column('state_of_origin', sa.String(length=20), nullable=True),
        sa.Column('lga_of_origin', sa.String(length=30), nullable=True),
        sa.Column('residential_address', sa.String(length=20), nullable=True),
        sa.Column('nationality', sa.String(length=20), nullable=True),
        sa.Column('nin', sa.String(length=250), nullable=True),
        sa.Column('bvn', sa.String(length=250), nullable=True),
        sa.Column('nin_is_verified', sa.Boolean(), nullable=False),
        sa.Column('bvn_is_verified', sa.Boolean(), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_user_kycs_user_id'),
        'user_kycs',
        ['user_id'],
        unique=True
    )

    op.create_table(
        'users_api_key',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('api_key', sa.String(length=250), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_users_api_key_user_id'),
        'users_api_key',
        ['user_id'],
        unique=True
    )

    op.create_table(
        'provider_disco_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('provider_name', sa.String(length=20), nullable=False),
        sa.Column('provider_plan_id', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ['plan_id'],
            ['disco_plans.id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['provider_name'],
            ['providers.name']
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.drop_table('provider_disco_types')

    op.add_column(
        'airtime_plans',
        sa.Column('discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'airtime_plans',
        sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'airtime_plans',
        sa.Column('agent_discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'airtime_plans',
        sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'airtime_plans',
        sa.Column('api_discount_type', sa.String(length=20), nullable=True)
    )

    # Temporary default allows existing rows to satisfy NOT NULL.
    op.add_column(
        'cable_plans',
        sa.Column(
            'name',
            sa.String(length=50),
            nullable=False,
            server_default=''
        )
    )

    # Remove the permanent database default.
    op.alter_column(
        'cable_plans',
        'name',
        server_default=None
    )

    op.add_column(
        'cable_plans',
        sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'cable_plans',
        sa.Column('discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'cable_plans',
        sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'cable_plans',
        sa.Column('agent_discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'cable_plans',
        sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'cable_plans',
        sa.Column('api_discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'cable_plans',
        sa.Column('description', sa.Text(), nullable=True)
    )

    op.drop_column('cable_plans', 'plan_name')

    op.add_column(
        'data_plans',
        sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'data_plans',
        sa.Column('discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'data_plans',
        sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'data_plans',
        sa.Column('agent_discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'data_plans',
        sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'data_plans',
        sa.Column('api_discount_type', sa.String(length=20), nullable=True)
    )

    # Temporary default allows existing rows to satisfy NOT NULL.
    op.add_column(
        'disco_plans',
        sa.Column(
            'type',
            sa.String(length=20),
            nullable=False,
            server_default=''
        )
    )

    # Remove the permanent database default.
    op.alter_column(
        'disco_plans',
        'type',
        server_default=None
    )

    op.add_column(
        'disco_plans',
        sa.Column('discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'disco_plans',
        sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'disco_plans',
        sa.Column('agent_discount_type', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'disco_plans',
        sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        'disco_plans',
        sa.Column('api_discount_type', sa.String(length=20), nullable=True)
    )

    op.alter_column(
        'disco_plans',
        'discount',
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True
    )

    op.drop_column('disco_plans', 'disco_type')

    op.add_column(
        'transactions',
        sa.Column('request_id', sa.String(length=250), nullable=True)
    )
    op.add_column(
        'transactions',
        sa.Column('service_from', sa.String(length=30), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('first_name', sa.String(length=50), nullable=True)
    )
    op.add_column(
        'users',
        sa.Column('middle_name', sa.String(length=50), nullable=True)
    )
    op.add_column(
        'users',
        sa.Column('last_name', sa.String(length=50), nullable=True)
    )
    op.add_column(
        'users',
        sa.Column('is_agent', sa.Boolean(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_agent')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_column('transactions', 'service_from')
    op.drop_column('transactions', 'request_id')
    op.add_column('disco_plans', sa.Column('disco_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('disco_plans', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('disco_plans', 'api_discount_type')
    op.drop_column('disco_plans', 'api_discount')
    op.drop_column('disco_plans', 'agent_discount_type')
    op.drop_column('disco_plans', 'agent_discount')
    op.drop_column('disco_plans', 'discount_type')
    op.drop_column('disco_plans', 'type')
    op.drop_column('data_plans', 'api_discount_type')
    op.drop_column('data_plans', 'api_discount')
    op.drop_column('data_plans', 'agent_discount_type')
    op.drop_column('data_plans', 'agent_discount')
    op.drop_column('data_plans', 'discount_type')
    op.drop_column('data_plans', 'discount')
    op.add_column('cable_plans', sa.Column('plan_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('cable_plans', 'description')
    op.drop_column('cable_plans', 'api_discount_type')
    op.drop_column('cable_plans', 'api_discount')
    op.drop_column('cable_plans', 'agent_discount_type')
    op.drop_column('cable_plans', 'agent_discount')
    op.drop_column('cable_plans', 'discount_type')
    op.drop_column('cable_plans', 'discount')
    op.drop_column('cable_plans', 'name')
    op.drop_column('airtime_plans', 'api_discount_type')
    op.drop_column('airtime_plans', 'api_discount')
    op.drop_column('airtime_plans', 'agent_discount_type')
    op.drop_column('airtime_plans', 'agent_discount')
    op.drop_column('airtime_plans', 'discount_type')
    op.create_table('provider_disco_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_disco_type_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], name=op.f('provider_disco_types_provider_name_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_disco_types_pkey'))
    )
    op.drop_table('provider_disco_plans')
    op.drop_index(op.f('ix_users_api_key_user_id'), table_name='users_api_key')
    op.drop_table('users_api_key')
    op.drop_index(op.f('ix_user_kycs_user_id'), table_name='user_kycs')
    op.drop_table('user_kycs')
    op.drop_index(op.f('ix_provider_exams_exam_id'), table_name='provider_exams')
    op.drop_table('provider_exams')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_table('kyc_plans')
    op.drop_index(op.f('ix_exam_plans_exam_id'), table_name='exam_plans')
    op.drop_table('exam_plans')
    op.drop_index(op.f('ix_bonus_transactions_user_id'), table_name='bonus_transactions')
    op.drop_index(op.f('ix_bonus_transactions_status'), table_name='bonus_transactions')
    op.drop_index(op.f('ix_bonus_transactions_reference'), table_name='bonus_transactions')
    op.drop_table('bonus_transactions')
    op.drop_table('exams')
    op.drop_table('bulk_sms_plans')
    # ### end Alembic commands ###
