"""create initial tables

Revision ID: bae2994cb0dd
Revises: 4624bf0973d1
Create Date: 2026-09-22 13:00:11.797634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae2994cb0dd'
down_revision: Union[str, Sequence[str], None] = '4624bf0973d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nin', sa.String(length=250), nullable=True),
    sa.Column('bvn', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bvn'),
    sa.UniqueConstraint('nin')
    )
    op.create_table('bulk_sms_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('general_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_link', sa.String(length=300), nullable=True),
    sa.Column('x_link', sa.String(length=300), nullable=True),
    sa.Column('facebook_link', sa.String(length=300), nullable=True),
    sa.Column('tiktok_link', sa.String(length=300), nullable=True),
    sa.Column('instagram_link', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('pin', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_agent', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_number'), 'users', ['number'], unique=True)
    op.create_table('airtime_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('minimum_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('agent_discount_type', sa.String(length=20), nullable=True),
    sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('api_discount_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vend_from', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vend_from'], ['providers.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=250), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_transactions_reference'), 'bonus_transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_bonus_transactions_status'), 'bonus_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_bonus_transactions_user_id'), 'bonus_transactions', ['user_id'], unique=False)
    op.create_table('cable_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cable_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('agent_discount_type', sa.String(length=20), nullable=True),
    sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('api_discount_type', sa.String(length=20), nullable=True),
    sa.Column('validity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('vend_from', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vend_from'], ['providers.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('agent_discount_type', sa.String(length=20), nullable=True),
    sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('api_discount_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('vend_from', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vend_from'], ['providers.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_plans_is_active'), 'data_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_data_plans_size'), 'data_plans', ['size'], unique=False)
    op.create_index(op.f('ix_data_plans_validity'), 'data_plans', ['validity'], unique=False)
    op.create_table('disco_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disco_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('minimum_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('agent_discount_type', sa.String(length=20), nullable=True),
    sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('api_discount_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vend_from', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['disco_id'], ['discos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vend_from'], ['providers.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('agent_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('agent_discount_type', sa.String(length=10), nullable=False),
    sa.Column('api_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('api_discount_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_plans_exam_id'), 'exam_plans', ['exam_id'], unique=False)
    op.create_table('kyc_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['provider'], ['payment_providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_type')
    )
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=250), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.Column('token_expiry_time', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('charges_type', sa.String(length=30), nullable=False),
    sa.Column('flat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capped', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['provider'], ['payment_providers.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'bank_code')
    )
    op.create_index(op.f('ix_payment_plans_bank_code'), 'payment_plans', ['bank_code'], unique=False)
    op.create_table('plan_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['provider'], ['providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'plan_id')
    )
    op.create_index(op.f('ix_plan_routes_plan_id'), 'plan_routes', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_routes_service'), 'plan_routes', ['service'], unique=False)
    op.create_table('provider_cables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=20), nullable=False),
    sa.Column('cable_id', sa.Integer(), nullable=False),
    sa.Column('provider_cable_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_discos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=20), nullable=False),
    sa.Column('disco_id', sa.Integer(), nullable=False),
    sa.Column('provider_disco_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['disco_id'], ['discos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('provider_exam_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_exams_exam_id'), 'provider_exams', ['exam_id'], unique=False)
    op.create_table('provider_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=20), nullable=True),
    sa.Column('provider_network_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=250), nullable=False),
    sa.Column('request_id', sa.String(length=250), nullable=True),
    sa.Column('provider_reference', sa.String(length=250), nullable=True),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('service_provider', sa.String(length=20), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=True),
    sa.Column('product', sa.String(length=50), nullable=True),
    sa.Column('beneficiary', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.Column('api_response', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('service_from', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_beneficiary'), 'transactions', ['beneficiary'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_service'), 'transactions', ['service'], unique=False)
    op.create_index(op.f('ix_transactions_service_provider'), 'transactions', ['service_provider'], unique=False)
    op.create_index(op.f('ix_transactions_service_type'), 'transactions', ['service_type'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_kycs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('state_of_origin', sa.String(length=20), nullable=True),
    sa.Column('lga_of_origin', sa.String(length=30), nullable=True),
    sa.Column('residential_address', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=20), nullable=True),
    sa.Column('nin', sa.String(length=250), nullable=True),
    sa.Column('bvn', sa.String(length=250), nullable=True),
    sa.Column('nin_is_verified', sa.Boolean(), nullable=False),
    sa.Column('bvn_is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_kycs_user_id'), 'user_kycs', ['user_id'], unique=True)
    op.create_table('users_api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key_user_id'), 'users_api_key', ['user_id'], unique=True)
    op.create_table('virtual_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('account_reference', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['provider'], ['payment_providers.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_reference')
    )
    op.create_index(op.f('ix_virtual_accounts_user_id'), 'virtual_accounts', ['user_id'], unique=False)
    op.create_table('walletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walletes_user_id'), 'walletes', ['user_id'], unique=True)
    op.create_table('provider_cable_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider_plan_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['cable_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_data_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=20), nullable=True),
    sa.Column('provider_plan_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['data_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_disco_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=20), nullable=False),
    sa.Column('provider_plan_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['disco_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_disco_plans')
    op.drop_table('provider_data_plan')
    op.drop_table('provider_cable_plans')
    op.drop_index(op.f('ix_walletes_user_id'), table_name='walletes')
    op.drop_table('walletes')
    op.drop_index(op.f('ix_virtual_accounts_user_id'), table_name='virtual_accounts')
    op.drop_table('virtual_accounts')
    op.drop_index(op.f('ix_users_api_key_user_id'), table_name='users_api_key')
    op.drop_table('users_api_key')
    op.drop_index(op.f('ix_user_kycs_user_id'), table_name='user_kycs')
    op.drop_table('user_kycs')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_service_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_service_provider'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_service'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_beneficiary'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('provider_networks')
    op.drop_index(op.f('ix_provider_exams_exam_id'), table_name='provider_exams')
    op.drop_table('provider_exams')
    op.drop_table('provider_discos')
    op.drop_table('provider_cables')
    op.drop_index(op.f('ix_plan_routes_service'), table_name='plan_routes')
    op.drop_index(op.f('ix_plan_routes_plan_id'), table_name='plan_routes')
    op.drop_table('plan_routes')
    op.drop_index(op.f('ix_payment_plans_bank_code'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_table('kyc_plans')
    op.drop_index(op.f('ix_exam_plans_exam_id'), table_name='exam_plans')
    op.drop_table('exam_plans')
    op.drop_table('disco_plans')
    op.drop_index(op.f('ix_data_plans_validity'), table_name='data_plans')
    op.drop_index(op.f('ix_data_plans_size'), table_name='data_plans')
    op.drop_index(op.f('ix_data_plans_is_active'), table_name='data_plans')
    op.drop_table('data_plans')
    op.drop_table('cable_plans')
    op.drop_index(op.f('ix_bonus_transactions_user_id'), table_name='bonus_transactions')
    op.drop_index(op.f('ix_bonus_transactions_status'), table_name='bonus_transactions')
    op.drop_index(op.f('ix_bonus_transactions_reference'), table_name='bonus_transactions')
    op.drop_table('bonus_transactions')
    op.drop_table('airtime_plans')
    op.drop_index(op.f('ix_users_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_infos')
    op.drop_table('providers')
    op.drop_table('payment_providers')
    op.drop_table('networks')
    op.drop_table('general_messages')
    op.drop_table('exams')
    op.drop_table('discos')
    op.drop_table('cables')
    op.drop_table('bulk_sms_plans')
    op.drop_table('admin_ids')
    # ### end Alembic commands ###
